language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: UhZlyiAZXf6mYg2hQA9g82bj5SbW4f1Y9sVhze6QcW2e0F4Bw8+QQxyJ9siKYldUiYeqfNg3OEt3YBhMUSiV9QgbJE3+rFjuHyKaCoLjZjwMgd5YLRtIl659wdkIZaLuY2/JNtJqtsnNItXZop1DDMUt/Os9GPuxzSufsCSCv1qZtWvZeXikjL7QkyauSn8gtCiN4rKsBHQmKohfnHQrVTU9tQBfJVadtN+y9ySLad9jCJHFXggbwSxwkET/cybysdBg/tNl/dGSjJbQwoAn27+e4iSbDS9Cybmo+26CNitj9RJnZuO6yFWuNL59fgXJCPy/DSDnyoah9eFe4UEdssO0HP0Ax0nmZsLdeI1YOECuGnHb+IBgWdD8ajXpNigBYY6k2bQIllBAEnze5betjAUzfBP78p8GJZ0iKqf3MBHGKcqjGrCL5/kLauhKSFKqDK3mIeXBUIwbAweaSpJaHKIG37FZHPGcJEhDf1dR0uzEJ6MyFhJfLG7J3OYUx+Tc6UfysxBIl3jYm+t1wcuYUUyDL1cHTq2fxAJNiYtWEVJ4ej+dgDacCavid+TnFm3xhG7xUytSXtRtdSvQJA4zLPMC0UK4aIKmD2IeCGAwuyZj7MOYwpJ1TshbqFZDJuMRtZZle6ILSA0l2zV5lDZy7i8IfigwZb8vjL4mQZq6I4Y=
